### ISSUE TITLE
Some values are not correctly read from the configuration file

### ISSUE THREAD

**Issue by dmak** [ArtificalSUN/Kcalibrator#3]
Configuration files reads:
```
size = (140.0, 70.0)
retract = (4.0, 30.0)
bed_size = (220.0, 220.0)
```
however when application `Kcalibrator.exe` starts, Y-size of the pattern, Y-size of the bed and retraction speed are zero:

![image](https://user-images.githubusercontent.com/366965/104786640-c5795300-578d-11eb-9ffe-e1c2bc5b90f0.png)

In general some basic validation of input fields is suggested, as otherwise the program generates G-code that tries to print outside the print area.

**Comment by ArtificalSUN** [comment]
This screenshot is from an old version. Try using the latest one.

**Comment by dmak** [comment]
Thanks for update. Unfortunately new v1.0.2 does not start on Windows 7 x64 (v1.0.1 runs just fine):
![image](https://user-images.githubusercontent.com/366965/104814487-8390f100-580f-11eb-809c-8710ed24fd99.png)
Any way to produce debug information (e.g. log) to resolve the issue?

**Comment by ArtificalSUN** [comment]
@dmak , are you sure you are having this issue with v 1.0.2? Version 1.0.1 had exactly this behavior when config file was corrupted or from an older version. The only reason for v1.0.2 is to fix this issue. All executables are built in exactly the same way on the same system so I doubt the problem is in your operating system. What is the version string (first line in the output gcode) for the executable that works for you?

P.S. I should definitely think about some debugging information, currently nothing is available.

**Comment by dmak** [comment]
Yes, I have an issue with latest release, downloaded from [here](https://github.com/ArtificalSUN/Kcalibrator/releases/download/v1.0.2/kcalibrator.exe) (MD5 acf20380c409fb475acc1b7282945434). It does not start on Windows 7 and Windows 10.
Previous release, downloaded from [here](https://github.com/ArtificalSUN/Kcalibrator/releases/download/v0.2.0/Kcalibrator.exe) (MD5 a537b19682fc0612ce78973ac3b90c35) launches/runs just fine and generates the following start code:
```
M190 S60
    M109 S210
    M106 S127
```
Excuses, I have missed the right version number (should be v0.2.0 instead of 1.0.1 on my previous post).

**Comment by dmak** [comment]
I've got what was the issue. CFG file created by previous version, causes new version to fail. Namely, if
```
bed_size = (200.0, 200.0)
```
then the program crashes. Otherwise latest version runs just fine.
Anyway, the problem with loading values from saved configuration has been solved.
